# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: wipe4j
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache wipe4j mvn
      id: wipe4j-mvn
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cleanup local system cache
      run: sudo rm -rf ~/.m2/repository/com/github/daggerok
    - name: Install required local modules first
      run: ./mvnw -f wipe4j-core install
    - name: Resolve maven dependencies
      run: ./mvnw -B dependency:resolve-plugins dependency:resolve
    - name: Clean maven projects
      run: ./mvnw clean
    - name: Run maven tests
      run: ./mvnw test
  # disable local deploy triggered automatically as not needed
  test-local-deploy:
    if: github.event.inputs.git-ref != ''
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache wipe4j mvn
      id: wipe4j-mvn
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cleanup local system cache
      run: sudo rm -rf ~/.m2/repository/com/github/daggerok
    - name: Deploy maven artifacts locally
      run: ./mvnw -P local-deploy
  javadoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache wipe4j mvn
      id: wipe4j-mvn
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cleanup local system cache
      run: sudo rm -rf ~/.m2/repository/com/github/daggerok
    - name: Install required maven artifacts locally
      run: ./mvnw -f wipe4j-core clean install
    - name: Build javadoc
      run: ./mvnw javadoc:javadoc
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache wipe4j mvn
      id: wipe4j-mvn
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
    - name: Cache wipe4j npm
      id: wipe4j-npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Resolve maven dependencies
      run: ./mvnw -f docs -B dependency:resolve-plugins dependency:resolve
    - name: Build vuepress documentation
      run: ./mvnw -f docs -Pci
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/src/.vuepress/dist # The folder the action should deploy.
